# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-03-05 07:55+1000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: ceilometer/declarative.py:68
#, python-format
msgid "The field 'fields' is required for %s"
msgstr ""

#: ceilometer/declarative.py:81
#, python-format
msgid "Plugin specified, but no plugin name supplied for %s"
msgstr ""

#: ceilometer/declarative.py:90
#, python-format
msgid "No plugin named %(plugin)s available for %(name)s"
msgstr ""

#: ceilometer/declarative.py:116
#, python-format
msgid "Parse error in JSONPath specification '%(jsonpath)s' for %(name)s: %(err)s"
msgstr ""

#: ceilometer/declarative.py:181
#, python-format
msgid ""
"Invalid YAML syntax in Definitions file %(file)s at line: %(line)s, "
"column: %(column)s."
msgstr ""

#: ceilometer/declarative.py:187
#, python-format
msgid "YAML error reading Definitions file %(file)s"
msgstr ""

#: ceilometer/monasca_client.py:66
#, python-format
msgid "monasca_client: using %s as Monasca endpoint"
msgstr ""

#: ceilometer/notification.py:109
#, python-format
msgid "Could not load the following pipelines: %s"
msgstr ""

#: ceilometer/cmd/status.py:43
msgid "Sample Check"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:53
#, python-format
msgid ""
"Error from libvirt while looking up instance <name=%(name)s, id=%(id)s>: "
"[Error Code %(error_code)s] %(ex)s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:70
#, python-format
msgid ""
"Failed to inspect data of instance <name=%(name)s, id=%(id)s>, domain "
"state is SHUTOFF."
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:180
#, python-format
msgid ""
"Error from libvirt while checking blockStats, This may not be harmful, "
"but please check : %(ex)s"
msgstr ""

#: ceilometer/compute/virt/libvirt/utils.py:121
#, python-format
msgid ""
"Failed to inspect instance %(instance_uuid)s stats, can not get info from"
" libvirt: %(error)s"
msgstr ""

#: ceilometer/compute/virt/vmware/inspector.py:106
#, python-format
msgid "VM %s not found in VMware vSphere"
msgstr ""

#: ceilometer/compute/virt/vmware/inspector.py:112
#, python-format
msgid "VM %s is poweredOff in VMware vSphere"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:62
msgid "Must specify connection_url, and connection_password to use"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:70
#, python-format
msgid "Could not connect to XenAPI: %s"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:86
#, python-format
msgid "VM %s not found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:89
#, python-format
msgid "Multiple VM %s found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:106
#, python-format
msgid "Could not get VM %s CPU number"
msgstr ""

#: ceilometer/event/converter.py:53
#, python-format
msgid "Invalid trait type '%(type)s' for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:97 ceilometer/publisher/gnocchi.py:113
#, python-format
msgid "Required field %s not specified"
msgstr ""

#: ceilometer/event/converter.py:265
#, python-format
msgid "Dropping Notification %(type)s (uuid:%(msgid)s)"
msgstr ""

#: ceilometer/hardware/pollsters/generic.py:55
#, python-format
msgid "Missing field %s"
msgstr ""

#: ceilometer/hardware/pollsters/generic.py:58
#, python-format
msgid "Unrecognized type value %s"
msgstr ""

#: ceilometer/ipmi/platform/intel_node_manager.py:292
msgid "Node Manager init failed"
msgstr ""

#: ceilometer/ipmi/platform/ipmi_sensor.py:101
msgid "Wrong sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:40
msgid "parse IPMI sensor data failed,unknown sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:81
msgid "parse IPMI sensor data failed,No data retrieved from given input"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:103
msgid "ipmitool output length mismatch"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:129
msgid "running ipmitool failure"
msgstr ""

#: ceilometer/ipmi/pollsters/node.py:58
#, python-format
msgid "Polling %(name)s failed for %(cnt)s times!"
msgstr ""

#: ceilometer/ipmi/pollsters/node.py:62 ceilometer/ipmi/pollsters/sensor.py:67
#, python-format
msgid "Pollster for %s is disabled!"
msgstr ""

#: ceilometer/ipmi/pollsters/sensor.py:62
#, python-format
msgid "Polling %(mtr)s sensor failed for %(cnt)s times!"
msgstr ""

#: ceilometer/meter/notifications.py:58
#, python-format
msgid "Required fields %s not specified"
msgstr ""

#: ceilometer/meter/notifications.py:68
#, python-format
msgid "Invalid type %s specified"
msgstr ""

#: ceilometer/network/services/fwaas.py:47
#, python-format
msgid "Unknown status %(stat)s received on fw %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:86
#, python-format
msgid "Unknown status %(stat)s received on pool %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:133
#, python-format
msgid "Unknown status %(stat)s received on vip %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:173
#, python-format
msgid "Unknown status %(stat)s received on member %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:402
#, python-format
msgid "Unknown status %(stat)s received on listener %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:445
#, python-format
msgid "Unknown status %(stat)s received on Load Balancer %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/vpnaas.py:48
#, python-format
msgid "Unknown status %(stat)s received on vpn %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/statistics/opencontrail/client.py:53
#, python-format
msgid "Opencontrail API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/client.py:223
#: ceilometer/tests/unit/network/statistics/opendaylight/test_client.py:146
#, python-format
msgid "OpenDaylight API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/objectstore/rgw_client.py:50
#, python-format
msgid "RGW AdminOps API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/publisher/gnocchi.py:116
#, python-format
msgid "Required field %(field)s should be a %(type)s"
msgstr ""

#: ceilometer/publisher/messaging.py:94
#, python-format
msgid "Publishing policy is unknown (%s) force to default"
msgstr ""

#: ceilometer/publisher/messaging.py:148
#, python-format
msgid "Publisher max local_queue length is exceeded, dropping %d oldest samples"
msgstr ""

#: ceilometer/publisher/messaging.py:160
#, python-format
msgid "Failed to publish %d datapoints, queue them"
msgstr ""

#: ceilometer/publisher/messaging.py:164
#, python-format
msgid "Failed to publish %d datapoints, dropping them"
msgstr ""

#: ceilometer/publisher/udp.py:75
msgid "Unable to send sample over UDP"
msgstr ""

