# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
#
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
# Дронова Юлия <juliette.tux@gmail.com>, 2022.
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-03-01 19:18+1000\n"
"PO-Revision-Date: 2022-03-11 22:41+0300\n"
"Last-Translator: Дронова Юлия <juliette.tux@gmail.com>\n"
"Language-Team: RU\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"
"Language: ru\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<"
"=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Generator: Lokalize 21.12.2\n"

#: oslo_concurrency/lockutils.py:258
msgid "Specifying semaphores is not supported when using fair locks."
msgstr "При использовании fair lock настройка семафоров не поддерживается"

#: oslo_concurrency/lockutils.py:473
msgid ""
"Calling lockutils directly is no longer supported.  Please use the "
"lockutils-wrapper console script instead."
msgstr ""
"Прямые вызовы lockutils больше не поддерживаются. Используйте консольный "
"сценарий lockutils-wrapper."

#: oslo_concurrency/processutils.py:96
msgid "Unexpected error while running command."
msgstr "Непредвиденная ошибка при выполнении команды"

#: oslo_concurrency/processutils.py:102
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""
"%(description)s\n"
"Команда: %(cmd)s\n"
"Код выхода: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"

#: oslo_concurrency/processutils.py:342
#, python-format
msgid "Got unknown keyword args: %r"
msgstr "Получены аргументы неизвестного ключевого слова: %r"

#: oslo_concurrency/processutils.py:347
#, python-format
msgid "Got invalid arg log_errors: %r"
msgstr "Получен недопустимый аргумент log_errors: %r"

#: oslo_concurrency/processutils.py:353
msgid "Command requested root, but did not specify a root helper."
msgstr "Команда запросила root, но root helper не был указан."

#: oslo_concurrency/processutils.py:367
msgid ""
"Process resource limits are ignored as this feature is not supported on "
"Windows."
msgstr ""
"Лимиты ресурсов процесса игнорируются, поскольку эта возможность не"
" поддерживается "
"в Windows"

#: oslo_concurrency/processutils.py:384
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "Выполняется cmd (подпроцесс): %s"

#: oslo_concurrency/processutils.py:458
#, python-format
msgid ""
"%(desc)r\n"
"command: %(cmd)r\n"
"exit code: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"
msgstr ""
"%(desc)r\n"
"команда: %(cmd)r\n"
"код выхода: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"

#: oslo_concurrency/processutils.py:467
#, python-format
msgid ""
"Got an OSError\n"
"command: %(cmd)r\n"
"errno: %(errno)r"
msgstr ""
"Получена OSError\n"
"команда: %(cmd)r\n"
"errno: %(errno)r"

#: oslo_concurrency/processutils.py:473
#, python-format
msgid "%r failed. Not Retrying."
msgstr "Сбой %r. Повторных попыток не будет."

#: oslo_concurrency/processutils.py:477
#, python-format
msgid "%r failed. Retrying."
msgstr "Сбой %r. Повторяем попытку."

#: oslo_concurrency/processutils.py:544
msgid "Environment not supported over SSH"
msgstr "Доступ к окружению через SSH не поддерживается"

#: oslo_concurrency/processutils.py:548
msgid "process_input not supported over SSH"
msgstr "process_input не поддерживается через SSH"

