# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-03-23 12:23+1000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: keystonemiddleware/ec2_token.py:126
msgid "Signature not provided"
msgstr ""

#: keystonemiddleware/ec2_token.py:130
msgid "Access key not provided"
msgstr ""

#: keystonemiddleware/ec2_token.py:185
#, python-format
msgid "Error response from keystone: %s"
msgstr ""

#: keystonemiddleware/ec2_token.py:191
msgid "Failure parsing response from keystone"
msgstr ""

#: keystonemiddleware/auth_token/__init__.py:438
#: keystonemiddleware/auth_token/__init__.py:451
#: keystonemiddleware/auth_token/__init__.py:486
#: keystonemiddleware/auth_token/__init__.py:561
#: keystonemiddleware/auth_token/__init__.py:575
#: keystonemiddleware/auth_token/__init__.py:589
#: keystonemiddleware/auth_token/_identity.py:163
msgid "Token authorization failed"
msgstr ""

#: keystonemiddleware/auth_token/__init__.py:680
msgid "The request you have made requires authentication."
msgstr ""

#: keystonemiddleware/auth_token/__init__.py:786
msgid "Unable to determine service tenancy."
msgstr ""

#: keystonemiddleware/auth_token/_auth.py:135
msgid "Invalid version asked for in auth_token plugin"
msgstr ""

#: keystonemiddleware/auth_token/_cache.py:265
msgid ""
"memcache_secret_key must be defined when a memcache_security_strategy is "
"defined"
msgstr ""

#: keystonemiddleware/auth_token/_identity.py:58
#: keystonemiddleware/auth_token/_identity.py:179
msgid "Failed to fetch token data from identity server"
msgstr ""

#: keystonemiddleware/auth_token/_identity.py:139
msgid "No compatible apis supported by server"
msgstr ""

#: keystonemiddleware/auth_token/_identity.py:170
msgid "Identity server rejected authorization necessary to fetch token data"
msgstr ""

#: keystonemiddleware/auth_token/_memcache_crypt.py:164
msgid "Encrypted data appears to be corrupted."
msgstr ""

#: keystonemiddleware/auth_token/_memcache_crypt.py:208
msgid "Invalid MAC; data appears to be corrupted."
msgstr ""

